version: '3'

services:
  coordinator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: python -u /app/coordinator.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - strassen_network

  worker1:
    build: .
    volumes:
      - ./app:/app
    command: python -u /app/worker.py
    depends_on:
      - coordinator
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - strassen_network

  worker2:
    build: .
    volumes:
      - ./app:/app
    command: python -u /app/worker.py
    depends_on:
      - coordinator
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - strassen_network

  worker3:
    build: .
    volumes:
      - ./app:/app
    command: python -u /app/worker.py
    depends_on:
      - coordinator
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - strassen_network

  worker4:
    build: .
    volumes:
      - ./app:/app
    command: python -u /app/worker.py
    depends_on:
      - coordinator
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - strassen_network

networks:
  strassen_network:
    driver: bridge