networks:
  csce689-project-network:
    driver: bridge
services:
  coordinator:
    build: .
    command: python -u coordinator.py
    environment:
    - NODE_ID=coordinator
    - PORT=5000
    networks:
    - csce689-project-network
    ports:
    - 5000:5000
    volumes:
    - ./app/:/app
  worker1:
    build: .
    command: python -u worker.py
    container_name: worker1
    depends_on:
    - coordinator
    environment:
    - NODE_ID=1
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5001
    - MIN_MULT=16
    image: alpine:latest
    networks:
    - csce689-project-network
  worker2:
    build: .
    command: python -u worker.py
    container_name: worker2
    depends_on:
    - coordinator
    environment:
    - NODE_ID=2
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5002
    - MIN_MULT=16
    image: debian:stable-slim
    networks:
    - csce689-project-network
  worker3:
    build: .
    command: python -u worker.py
    container_name: worker3
    depends_on:
    - coordinator
    environment:
    - NODE_ID=3
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5003
    - MIN_MULT=16
    image: fedora:latest
    networks:
    - csce689-project-network
  worker4:
    build: .
    command: python -u worker.py
    container_name: worker4
    depends_on:
    - coordinator
    environment:
    - NODE_ID=4
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5004
    - MIN_MULT=16
    networks:
    - csce689-project-network
  worker5:
    build: .
    command: python -u worker.py
    container_name: worker5
    depends_on:
    - coordinator
    environment:
    - NODE_ID=5
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5005
    - MIN_MULT=16
    networks:
    - csce689-project-network
  worker6:
    build: .
    command: python -u worker.py
    container_name: worker6
    depends_on:
    - coordinator
    environment:
    - NODE_ID=6
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5006
    - MIN_MULT=16
    networks:
    - csce689-project-network
  worker7:
    build: .
    command: python -u worker.py
    container_name: worker7
    depends_on:
    - coordinator
    environment:
    - NODE_ID=7
    - COORDINATOR_HOST=coordinator
    - COORDINATOR_PORT=5000
    - PORT=5007
    - MIN_MULT=16
    networks:
    - csce689-project-network
