version: '3.8'
services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    environment:
      - NODE_ID=0
      - DELAY=0.5
    tty: true
    stdin_open: true
    volumes:
      - ./input.txt:/app/input.txt
    networks:
      - matrix-net

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ID=1
      - DELAY=1.0
    hostname: worker1
    networks:
      - matrix-net

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ID=2
      - DELAY=1.0
    hostname: worker2
    networks:
      - matrix-net

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ID=3
      - DELAY=1.0
    hostname: worker3
    networks:
      - matrix-net

  worker4:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ID=4
      - DELAY=1.0
    hostname: worker4
    networks:
      - matrix-net

  worker5:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ID=5
      - DELAY=1.0
    hostname: worker5
    networks:
      - matrix-net

networks:
  matrix-net:
    driver: bridge