version: '3'

services:
  coordinator:
    build: .
    container_name: coordinator
    ports:
      - "5000:5000"
    command: python -u coordinator.py
    networks:
      - strassen_network
    environment:
      - NODE_ID=coordinator
      - PORT=5000

  worker1:
    build: .
    container_name: worker1
    depends_on:
      - coordinator
    command: python -u worker.py
    networks:
      - strassen_network
    environment:
      - NODE_ID=1
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=5000
      - PORT=5001

  worker2:
    build: .
    container_name: worker2
    depends_on:
      - coordinator
    command: python -u worker.py
    networks:
      - strassen_network
    environment:
      - NODE_ID=2
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=5000
      - PORT=5002

  worker3:
    build: .
    container_name: worker3
    depends_on:
      - coordinator
    command: python -u worker.py
    networks:
      - strassen_network
    environment:
      - NODE_ID=3
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=5000
      - PORT=5003

  worker4:
    build: .
    container_name: worker4
    depends_on:
      - coordinator
    command: python -u worker.py
    networks:
      - strassen_network
    environment:
      - NODE_ID=4
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=5000
      - PORT=5004

networks:
  strassen_network:
    driver: bridge